version: "3.9"
name: "labeling"

services:

  labeling-database:
    container_name: labeling-database
    hostname: labeling-database
    image: seart/labeling-database:latest
    build:
      context: ../
      dockerfile: deployment/database/Dockerfile
    volumes:
      - data:/var/lib/postgresql/data
    networks: [ default ]
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASS}
    restart: always

  labeling-server:
    container_name: labeling-server
    hostname: labeling-server
    image: seart/labeling-server:latest
    build:
      context: ../
      dockerfile: deployment/server/Dockerfile
    networks: [ default ]
    environment:
      DATABASE_HOST: labeling-database
      DATABASE_PORT: 5432
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_PASS: ${DATABASE_PASS}
    depends_on:
      labeling-database:
        condition: service_healthy
    deploy:
      restart_policy:
        condition: on-failure
        max_attempts: 3
    ports:
      - "7755:3000"

volumes:
  data:
    name: labeling-data

networks:
  default:
    name: labeling-network
